[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = true
enableXsrfProtection = false
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[logger]
level = "warning"